apps/subscriptions/urls.py
from django.urls import path

from . import views


app_name = 'subscriptions'

urlpatterns = [
    path('api/active-products/', views.ProductWithMetadataAPI.as_view(), name='products_api'),
    path('', views.subscription, name='subscription_details'),

    # stripe checkout views
    path('checkout-success/', views.checkout_success, name='checkout_success'),
    path('checkout-canceled/', views.checkout_canceled, name='checkout_canceled'),

    # stripe integration views that return redirects to Stripe
    # these are the defaults
    path('stripe/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('stripe/portal/', views.create_portal_session, name='create_stripe_portal_session'),

    # stripe api views that return Stripe URLs instead of redirects
    # these can be used by JavaScript front-ends to handle the redirect from the response
    path('stripe/api/create-checkout-session/', views.CreateCheckoutSession.as_view(),
         name='api_create_checkout_session'),
    path('stripe/api/create-portal-session/', views.CreatePortalSession.as_view(), name='api_create_portal_session'),
]

apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('profile/', views.profile, name='user_profile'),
    path('profile/upload-image/', views.upload_profile_image, name='upload_profile_image'),
]

apps/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.home, name='home'),
    path('terms/', TemplateView.as_view(template_name="web/terms.html"), name='terms'),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
    path('simulate_error/', views.simulate_error),
    path('get_stats/', views.update_page_tiktokstats, name="get_stats"),
]

tiktok_insights/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.web.sitemaps import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap(),
}

urlpatterns = [
    # redirect Django admin login to main login page
    path('admin/login/', RedirectView.as_view(pattern_name='account_login')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('', include('apps.web.urls')),
    path('support/', include('apps.support.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI - you may wish to remove one of these depending on your preference
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # Add Guided Tour
    path('guided-tour/', include('apps.tiktokinfo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/web/components/app_nav.html
<ul class="menu bg-base-100 p-2 rounded-box">
  {% include 'web/components/app_nav_menu_items.html' %}
</ul>

templates/web/components/app_nav_menu_items.html
{% load i18n %}
<li class="menu-title">
  <span>{% translate "Application" %}</span>
</li>
<li>
    <a href="{% url 'web:home' %}" {% if active_tab == 'dashboard' %}class="active"{% endif %}>
        <i class="fa fa-home"></i>
        {% translate "Dashboard" %}
    </a>
</li>
<li>
  <a href="{% url 'tiktokinfo:home' %}" {% if active_tab == 'guided-tour' %}class="active"{% endif %}>
    <i class="fa fa-person-walking-arrow-right"></i>
    {% translate "Guided Tour" %}
  </a>
</li>
<li class="menu-title">
  <span>{% translate "My Account" %}</span>
</li>
<ul class="menu-list">
  <li>
    <a href="{% url 'subscriptions:subscription_details' %}" {% if active_tab == 'subscription' %}class="active"{% endif %}>
      <i class="fa fa-repeat"></i>
      Subscription
    </a>
  </li>
  <li>
    <a href="{% url 'users:user_profile' %}" {% if active_tab == 'profile' %}class="active"{% endif %}>
      <i class="fa fa-user"></i>
      {% translate "Profile" %}
    </a>
  </li>
  {% if user.has_usable_password %}
  <li>
    <a href="{% url 'account_change_password' %}" {% if 'accounts/password/change' in request.path %}class="active"{% endif %}>
      <i class="fa fa-unlock-alt"></i>
      {% translate "Change Password" %}
    </a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'account_logout' %}" {% if 'accounts/logout' in request.path %}class="active"{% endif %}>
      <i class="fa fa-sign-out"></i>
      {% translate "Sign out" %}
    </a>
  </li>
</ul>

templates/web/components/favicon.html
{% load static %}
{# see https://realfavicongenerator.net #}
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'images/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
<link rel="shortcut icon" href="{% static 'images/favicons/favicon.ico' %}">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-config" content="{% static 'images/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#ffffff">

templates/web/components/footer.html
{% load i18n %}
<footer class="mt-10 mb-4">
  <div class="text-center text-gray-700">
    <p>{{project_meta.NAME}} &mdash; {% translate "Copyright" %} <span id="copyright-year">2022</span></p>
    {% include "web/components/language_select.html" %}
  </div>
</footer>
<script>
    document.getElementById('copyright-year').innerText = (new Date()).getFullYear();
</script>

templates/web/components/google_analytics.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_ID  }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS_ID  }}');
</script>

templates/web/components/hero.html
{% load i18n %}
{% load static %}
<section class="my-8 mx-4">
  <div class="container ">
    <div class="pg-columns pg-columns-reversed pg-align-items-center">
      <div class="pg-column">
        <img class="img-fluid" src="{% static 'images/undraw/undraw_outer_space.svg' %}" alt="{% translate "Fly Away!" %}">
      </div>
      <div class="pg-column">
        <h1 class="pg-title">{{project_meta.NAME}}</h1>
        <h2 class="pg-subtitle">
          {{project_meta.DESCRIPTION}}
        </h2>
        <p class="buttons">
          <a class="pg-button-primary" href="{% url 'account_signup' %}">
            {% translate "Create account" %}
          </a>
          <a class="pg-button-secondary" href="{% url 'account_login' %}">
            {% translate "Sign In" %}
          </a>
        </p>
      </div>
    </div>
  </div>
</section>

templates/web/components/language_select.html
{% load i18n %}
{% if not user.is_authenticated and use_i18n %}
<div class="my-2">
  <form id="language-select" action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <select name="language" class="select select-bordered select-sm max-w-xs py-0">
      {% get_current_language as LANGUAGE_CODE %}
      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as languages %}
      {% for language in languages %}
        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
          {{ language.name_local }} ({{ language.code }})
        </option>
      {% endfor %}
    </select>
  </form>
</div>
<script>
  let form = document.getElementById("language-select"),
    langSelect = document.getElementsByName("language")[0];
  langSelect.onchange = () => {
    form.submit();
  };
</script>
{% endif %}

templates/web/components/messages-js.html
<script>
    document.addEventListener('DOMContentLoaded', () => {
      (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
        let $notification = $delete.parentNode;
        $delete.addEventListener('click', () => {
          $notification.parentNode.removeChild($notification);
        });
      });
    });
</script>

templates/web/components/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="notification flex w-full justify-between alert {% if message.tags %}alert-{{ message.level_tag }}{% endif %} shadow-md !rounded-none {{ message.extra_tags }} mb-1" >
      <div>{{ message }}</div>
      <button class="delete"><i class="fa fa-times"></i></button>
    </div>
  {% endfor %}
{% endif %}

templates/web/components/top_nav.html
{% load i18n %}
<div class="navbar bg-base-100 shadow-md">
  <div class="navbar-start">
    <div class="dropdown">
      <div class="lg:hidden">
        <label tabindex="0" class="btn btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
        </label>
      </div>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
        {% block mobile_nav %}
        <li>
          <a class="{% if request.path == '/' %}active{% endif %}" href="{% url 'web:home' %}">
            <div>{{project_meta.NAME}}</div>
          </a>
        </li>
        {% endblock %}
      </ul>
    </div>
  </div>
  <div class="navbar-center hidden lg:flex">
    <div class="menu menu-horizontal p-0">
      <a class="tab {% if request.path == '/' %}tab-active{% endif %}" href="{% url 'web:home' %}">
        <div>{{project_meta.NAME}}</div>
      </a>
    </div>
  </div>
  <div class="navbar-end">
    {% if not user.is_authenticated %}
    <a href="{% url 'account_signup' %}" class="btn btn-primary">
      {% translate "Sign Up" %}
    </a>
    <a href="{% url 'account_login' %}" class="btn btn-outline ml-2">
      {% translate "Sign In" %}
    </a>
    {% endif %}
  </div>
</div>

templates/web/components/top_nav_app.html
{% extends 'web/components/top_nav.html' %}
{% block mobile_nav %}
  <li class="menu-title">
    <span>Site</span>
  </li>
  {{ block.super }}
  {% include 'web/components/app_nav_menu_items.html' %}
{% endblock %}