apps/subscriptions/urls.py
from django.urls import path

from . import views


app_name = 'subscriptions'

urlpatterns = [
    path('api/active-products/', views.ProductWithMetadataAPI.as_view(), name='products_api'),
    path('', views.subscription, name='subscription_details'),

    # stripe checkout views
    path('checkout-success/', views.checkout_success, name='checkout_success'),
    path('checkout-canceled/', views.checkout_canceled, name='checkout_canceled'),

    # stripe integration views that return redirects to Stripe
    # these are the defaults
    path('stripe/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('stripe/portal/', views.create_portal_session, name='create_stripe_portal_session'),

    # stripe api views that return Stripe URLs instead of redirects
    # these can be used by JavaScript front-ends to handle the redirect from the response
    path('stripe/api/create-checkout-session/', views.CreateCheckoutSession.as_view(),
         name='api_create_checkout_session'),
    path('stripe/api/create-portal-session/', views.CreatePortalSession.as_view(), name='api_create_portal_session'),
]

apps/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.home, name='home'),
    path('terms/', TemplateView.as_view(template_name="web/terms.html"), name='terms'),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
    path('simulate_error/', views.simulate_error),
    path('get_stats/', views.update_page_tiktokstats, name="get_stats"),
]

tiktok_insights/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from apps.web.sitemaps import StaticViewSitemap


sitemaps = {
    'static': StaticViewSitemap(),
}

urlpatterns = [
    # redirect Django admin login to main login page
    path('admin/login/', RedirectView.as_view(pattern_name='account_login')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('', include('apps.web.urls')),
    path('support/', include('apps.support.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI - you may wish to remove one of these depending on your preference
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # Add Guided Tour
    path('guided-tour/', include('apps.tiktokinfo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/web/app_home.html
{% extends "web/app/app_base.html" %}
{% load i18n %}
{% load static %}
{% block app %}
<section class="app-main-head">
    <div class="pg-columns pg-columns-reversed pg-align-items-center">
        <div class="pg-column-one-third">
            <img class="img-fluid" src="{% static 'images/undraw/undraw_outer_space.svg' %}"
            alt="{% translate "Rocket Your TikTok Ranking!" %}">
        </div>
        <div class="pg-column">
            <h1 class="pg-title">{% translate "You're Signed Into TikTok Insights!" %}</h1>
            <h2 class="pg-subtitle">
                {% if subscription %}
                   <div class="my-2 pg-text-centered pg-text-success">
                    <p> {% translate "This is TikTok Insight's Stastics for " %} {{user_info.unique_id}}</p>
                    <br>
                    <p> {% translate "You're subscribed! Hooray!" %}</p>
                   </div>
                {% else %}
                    <div class="my-2 pg-text-centered pg-text-info">
                    <p>{% translate "Whoops! It doesn't look like you're subscribed." %}</p>
                    <p>{% translate "You'll need to subscribe to see your statistics." %}</p>
                    <p><a href="{% url 'subscriptions:subscription_details' %}"><strong>Upgrade Here!</strong></a></p>
                    </div>
                {% endif %}
            </h2>
        </div>
    </div>
</section>


<div class="divider"></div>
<h2>TikTok Stats</h2>
  {% include 'tiktok_info/tiktok_user_stats.html' %}

<div class="divider"></div>
<h2>TikTok Ranking Advice</h2>
  {% include 'tiktok_info/tiktok_advice.html' %}

<div class="divider"></div>
<h2>Charts</h2>
  {% include 'tiktok_info/tiktok_charts.html' %}

<div class="divider"></div>
<h2>TikTok User Stats (Version 2)</h2>
  {% include 'tiktok_info/tiktok_user_stats2.html' %}
<div class="divider divider-1"></div>

<!-- Style CSS -->
<style>
    /* Tooltip container */
    .tooltip {
        position: relative;
        display: inline-block;
        border-bottom: 1px dotted black;
        /* If you want dots under the hoverable text */
    }

    /* Tooltip text */
    .tooltip .tooltiptext {
        visibility: hidden;
        width: 120px;
        background-color: black;
        color: #fff;
        text-align: center;
        padding: 5px 0;
        border-radius: 6px;

        /* Position the tooltip text - see examples below! */
        position: absolute;
        z-index: 1;
    }

    /* Show the tooltip text when you mouse over the tooltip container */
    .tooltip:hover .tooltiptext {
        visibility: visible;
    }

    /* CSS for allowing the tooltip to overflow div */
    .stats {
        overflow: visible;
    }

    /* Style the button that is used to open and close the collapsible content */
    .collapsible {
        background-color: white;
        color: white;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
        border-radius: 10px;
    }

    /* Adds Icons */
    .collapsible:after {
        content: '\02795';
        /* Unicode character for "plus" sign (+) */
        font-size: 1rem;
        color: white;
        float: right;
        margin-left: 5px;
    }

    .active:after {
        content: "\2796";
        /* Unicode character for "minus" sign (-) */
        color: white;
    }

    /* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
    .active,
    .collapsible:hover {
        background-color: #de3bb4;
    }

    /* Style the collapsible content. Note: hidden by default */
    .content {
        padding: 0 18px;
        overflow: hidden;
        background-color: #d624a8;
        color: white;
        max-height: 0;
        transition: max-height 0.2 ease-out;
        margin-top: -10px;
        border-radius: 10px;
    }

    #collapsible-one {
        margin-top: 5.5rem;
    }

    .collapsible {
        background-color: #d624a8;
    }

    /* Loader */
    .loader {
        display: none;
        top: 50%;
        left: 50%;
        position: absolute;
        transform: translate(-50%, -50%);
    }

    .loading {
        border: 1.25rem solid #ccc;
        width: 8rem;
        height: 8rem;
        border-radius: 50%;
        border-top-color: #1ecd97;
        border-left-color: #1ecd97;
        animation: spin 2s infinite ease-in;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>
<!-- End Style CSS -->

<!-- Collapsible Javascript Start -->
<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.maxHeight) {
                content.style.maxHeight = null;
            } else {
                content.style.maxHeight = content.scrollHeight + "px";
            }
        });
    }
</script>
<!-- Collapsible Javascript End -->

<!-- Spinner Javascript Start -->
<script type="text/javascript">
    function spinner() {
        document.getElementsByClassName("loader")[0].style.display = "block";
    }
</script>
<!-- Spinner Javascript End -->

<!-- Test Components -->
<section class="top-tags">
    <div class="py-12">
        <h1 class="text-2xl text-center">Top Hashtags</h1>
    </div>
    <div class="overflow-x-auto">
        <table class="table w-full">
            <thead>
                <tr>
                    <th></th>
                    <th>Tag Name</th>
                    <th>Estimated True Mean Views</th>
                    <th>Average Views</th>
                    <th>Number of Videos with Tag</th>
                </tr>
            </thead>
            <tbody>
                <tr class="hover">
                    <th>1</th>
                    <td>oscarsathome</td>
                    <td>87,721</td>
                    <td>141,133</td>
                    <td>298,300</td>
                </tr>
                <tr class="hover">
                    <th>2</th>
                    <td>tiktokpartner</td>
                    <td>67,721</td>
                    <td>102,537</td>
                    <td>287,700</td>
                </tr>
                <tr class="hover">
                    <th>3</th>
                    <td>prank</td>
                    <td>65,253</td>
                    <td>71,166</td>
                    <td>1,200,000</td>
                </tr>
                <tr class="hover">
                    <th>4</th>
                    <td>makenightsepic</td>
                    <td>53,230</td>
                    <td>62,249</td>
                    <td>624,900</td>
                </tr>
                <tr class="hover">
                    <th>5</th>
                    <td>teentigada</td>
                    <td>52,398</td>
                    <td>71,469</td>
                    <td>347,000</td>
                </tr>
            </tbody>
        </table>
    </div>
</section>

<section class="app-card">
    <div class="pg-content">
        <div class="username-form">
            <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST"
                action="{% url 'web:get_stats' %}">
                {% csrf_token %}
                <span class="label-text" for="tkusername">
                    Enter TikTok Username
                </span>
                <input type="text" placeholder="@charlidemelio" id="tkusername" name="tkusername"
                    class="input input-bordered input-primary w-full max-w-xs" />
                <button type="submit" class="sbtn btn btn-secondary btn-c" onclick="spinner()">Get Stats</button>
                <div class="loader">
                    <div class="loading">
                    </div>
                </div>
        </div>
    </div>
</section>

{% endblock %}

templates/web/base.html
{% load static %}
{% load meta_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--IE compatibility-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--Mobile friendly-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% if project_meta %}
  {% with project_meta|get_title:page_title as title %}
  {% with project_meta|get_description:page_description as description %}
  {% with project_meta|get_image_url:page_image as image %}
      <title>{% block page_title %}{{ title }}{% endblock %}</title>
      <meta name="description" content="{{ description }}">
      <meta name="keywords" content="{{ project_meta.KEYWORDS }}">
      <!-- Twitter Card data -->
      <meta name="twitter:card" content="summary">
      <meta name="twitter:title" content="{{ title }}">
      <meta name="twitter:description" content="{{ description }}">
      <meta name="twitter:image" content="{{ image }}">
      <!-- Open Graph data -->
      <meta property="og:title" content="{{ title }}" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="{{ page_url }}" />
      <meta property="og:image" content="{{ image }}" />
      <meta property="og:description" content="{{ description }}" />
      <meta property="og:site_name" content="{{ project_meta.NAME }}" />
      <link rel="canonical" href="{% if page_canonical_url %}{{ page_canonical_url }}{% else %}{{ page_url }}{% endif %}">
  {% endwith %}
  {% endwith %}
  {% endwith %}
{% endif %}
{% include 'web/components/favicon.html' %}
    <link rel="stylesheet" href="{% static 'css/site-base.css' %}">
    <link rel="stylesheet" href="{% static 'css/site-tailwind.css' %}">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/v4-shims.min.css" integrity="sha512-ARfx5eajdcCAuWvuJrgUuJ6D25ON3KZRTCghNXXKeJldCQJ5bXS+6CvG2EhcFWITF95uwZydzpufSKvhmSpTxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% if GOOGLE_ANALYTICS_ID %}
        {% include 'web/components/google_analytics.html' %}
    {% endif %}
    <script type="text/javascript">__cssFramework = 'tailwind';</script>
    <script src="{% url 'javascript-catalog' %}"></script>
    {% block page_head %}
    {% endblock %}
</head>
<body>
{% block body_wrapper %}
{% block top_nav %}
  {% include 'web/components/top_nav.html' %}
{% endblock %}
{% block messages %}
  {% include 'web/components/messages.html' %}
{% endblock messages %}
{% block body %}
{% endblock body %}
{% block footer %}
  {% include 'web/components/footer.html' %}
{% endblock footer %}
{% endblock body_wrapper %}
{% block page_js %}
{% endblock page_js %}
  {% include 'web/components/messages-js.html' %}
</body>
</html>

templates/web/landing_page.html
{% extends "web/base.html" %}
{% load static %}
{% block body %}
  {% include 'web/components/hero.html' %}
{% endblock %}

templates/web/terms.html
{% extends "web/base.html" %}
{% load static %}
{% block body %}
<section class="section mt-7">
  <div class="container">
    <div class="pg-content">
      <h1>Terms Of Service</h1>
      <p>Your site's terms go here.</p>
    </div>
  </div>
</section>
{% endblock %}